### ISSUE TITLE
Help required in creating a Blog Post Page

### ISSUE THREAD

**Issue by TheFreedomCode** [TheFreedomCodes/FreedomCodeSite#6]
Hey! We require a Blog Post page for our site. The requirements are simple:

- The page should match the theme of our site.
- The page should be present on the navbar.
- The page should be simple and easy to use.

Any suggestions or contributions are appreciated.

**Comment by Ayan7858** [comment]
Hey, I am interested in helping you guys by enhancing your website by creating the blog post required.

**Comment by sumanthsumu1418** [comment]
happy to pick this one
