### ISSUE TITLE
Contact Form submitted notification.

### ISSUE THREAD

**Issue by TheFreedomCode** [TheFreedomCodes/FreedomCodeSite#7]
Hey! We require an enhancement on the contact form on our website. The form submitted must notify us(TheFreedomCode) about the form details.

Any suggestions or/and contributions are appreciated.

**Comment by sumanthsumu1418** [comment]
happy to pick this one

**Comment by RJ2601** [comment]
Hey..I am interested in solving this issue.

**Comment by Muhammad0320** [comment]
I want to work on this issue and solve it
